import React from 'react'
export const metadata = {
    title: 'About Github',
    description: 'Generated by create next app',
  }
  
const AboutPage = () => {
  return (
    <div>
        <h1>About My Github</h1>
        <p>
       
        Exercitationem assumenda culpa fuga consequatur non doloribus. A et error molestiae eligendi 
        Saepe quasi illo molestiae soluta dignissimos laborum sequi, maiores facilis temporibus possimus culpa maxime perferendis sed recusandae? Voluptas vitae fugit eius facilis, adipisci voluptatum nam recusandae quas repellat quisquam nemo?
        Voluptas consequatur mollitia rerum obcaecati tenetur molestiae natus veniam numquam maxime officiis, ipsa sed ut eos quia earum repellat. Quisquam repellat autem, perferendis minima magnam similique fugit error. Exercitationem, maiores?

        </p>
    </div>
  )
}

export default AboutPage