import './globals.css'
import { Poppins } from 'next/font/google'
import Header from './components/Header'
const popins = Poppins({
  weight: ['400','700'],
  subsets:['latin']
})
export const metadata = {
  title: 'My Github',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={popins.className}>
        <Header/>
        <main className="container">
        {children}
        </main>
      </body>
    </html>
  )
}
