import React from 'react'
export const metadata = {
  title: 'Team',
  description: 'Generated by create next app',
}

const TeamPage = () => {
  return (
    <div>
        <h1>My Team</h1>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repellat, excepturi?Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis, odit.</p>
    </div>
  )
}

export default TeamPage